name: Tag and push npm package and create a version release.

on:
  push:
    branches:
    - "feat/move-to-github-npm"

jobs:
  publish:
    name: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: NPM Install.
      run: npm ci

    - name: Setup git bot.
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: NPM build.
      run: npm run build

    - name: NPM Version.
      run: npm version patch

    - name: Push tag.
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.HBG_GH_TOKEN }}
        tags: true
        branch: ${{ github.ref }}

    - name: Inject access token in .npmrc
      run: | 
        echo "@helsingborg-stad:registry=https://npm.pkg.github.com/helsingborg-stad" >> ~/.npmrc
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.HBG_GH_TOKEN }}" >> ~/.npmrc

    - name: NPM Publish.
      run: npm publish
